namespace OpenOrderFramework.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class BigChange : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.CodeKinds");
            DropPrimaryKey("dbo.Codes");
            DropPrimaryKey("dbo.CombProduct_d");
            DropPrimaryKey("dbo.CombProduct_m");
            DropPrimaryKey("dbo.Companies");
            DropPrimaryKey("dbo.Factories");
            DropPrimaryKey("dbo.LongOrder_m");
            DropPrimaryKey("dbo.Order_d");
            DropPrimaryKey("dbo.Order_m");
            DropPrimaryKey("dbo.Params");
            DropPrimaryKey("dbo.Privileges");
            DropPrimaryKey("dbo.ProductKinds");
            DropPrimaryKey("dbo.Products");
            DropPrimaryKey("dbo.Programs");
            DropPrimaryKey("dbo.Stocks");
            DropPrimaryKey("dbo.UserGroup_d");
            DropPrimaryKey("dbo.UserGroup_m");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.Warehouses");
            CreateTable(
                "dbo.Customers",
                c => new
                    {
                        CustomerID = c.String(nullable: false, maxLength: 16),
                        CustName = c.String(nullable: false, maxLength: 40),
                        CustPassword = c.String(nullable: false, maxLength: 20),
                        ShortName = c.String(nullable: false, maxLength: 12),
                        SexType = c.String(nullable: false, maxLength: 1),
                        CustLevel = c.String(maxLength: 10),
                        CustType = c.String(maxLength: 10),
                        ContactName = c.String(maxLength: 20),
                        TelephoneNumber = c.String(maxLength: 15),
                        MobileNumber = c.String(maxLength: 15),
                        Email = c.String(maxLength: 50),
                        EmailValidated = c.String(maxLength: 1),
                        TaxID = c.String(maxLength: 10),
                        PostalCode = c.String(maxLength: 6),
                        Address = c.String(maxLength: 150),
                        PostalCode2 = c.String(maxLength: 6),
                        Address2 = c.String(maxLength: 150),
                        Memo = c.String(maxLength: 120),
                        ValidDate = c.DateTime(nullable: false),
                        InValidDate = c.DateTime(nullable: false),
                        StoredPoint = c.Int(nullable: false),
                        Birthday = c.DateTime(nullable: false),
                        Job = c.String(maxLength: 3),
                        CreateUserID = c.String(nullable: false, maxLength: 14),
                        CreateDateTime = c.DateTime(nullable: false),
                        ModifyUserID = c.String(nullable: false, maxLength: 14),
                        ModifyDateTime = c.DateTime(nullable: false),
                    })
                .PrimaryKey(t => t.CustomerID);
            
            AddColumn("dbo.CodeKinds", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.CodeKinds", "Code_KindName", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.CodeKinds", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CodeKinds", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CodeKinds", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CodeKinds", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Codes", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Codes", "CodeID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Codes", "CodeName", c => c.String(maxLength: 50));
            AddColumn("dbo.Codes", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Codes", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Codes", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Codes", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CombProduct_d", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.CombProduct_d", "CombProductID", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.CombProduct_d", "CombProdSeq", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.CombProduct_d", "ProductID", c => c.String(maxLength: 16));
            AddColumn("dbo.CombProduct_d", "OtherProductID", c => c.String(maxLength: 1));
            AddColumn("dbo.CombProduct_d", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CombProduct_d", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CombProduct_d", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CombProduct_d", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CombProduct_m", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.CombProduct_m", "CombProductID", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.CombProduct_m", "CombProdName", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.CombProduct_m", "CombProdSpec", c => c.String(nullable: false));
            AddColumn("dbo.CombProduct_m", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CombProduct_m", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CombProduct_m", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CombProduct_m", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Companies", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Companies", "CompanyName", c => c.String(nullable: false, maxLength: 40));
            AddColumn("dbo.Companies", "ShortName", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Companies", "PhoneCountryCode", c => c.String(maxLength: 3));
            AddColumn("dbo.Companies", "PhoneAreaCode", c => c.String(maxLength: 1));
            AddColumn("dbo.Companies", "PhoneNumber", c => c.String(maxLength: 15));
            AddColumn("dbo.Companies", "FaxNumber", c => c.String(maxLength: 15));
            AddColumn("dbo.Companies", "CompanyAddress", c => c.String(maxLength: 150));
            AddColumn("dbo.Companies", "Site", c => c.String(maxLength: 150));
            AddColumn("dbo.Companies", "Email", c => c.String(maxLength: 50));
            AddColumn("dbo.Companies", "BusinessHourS", c => c.String(maxLength: 5));
            AddColumn("dbo.Companies", "BusinessHourE", c => c.String(maxLength: 5));
            AddColumn("dbo.Companies", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Companies", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Companies", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Companies", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Factories", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Factories", "FactoryID", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Factories", "ShortName", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Factories", "FactoryName", c => c.String(nullable: false, maxLength: 40));
            AddColumn("dbo.Factories", "PostalCode", c => c.String(maxLength: 6));
            AddColumn("dbo.Factories", "FactoryAddress", c => c.String(maxLength: 150));
            AddColumn("dbo.Factories", "ChargeName", c => c.String(maxLength: 10));
            AddColumn("dbo.Factories", "PhoneCountryCode", c => c.String(maxLength: 3));
            AddColumn("dbo.Factories", "PhoneAreaCode", c => c.String(maxLength: 4));
            AddColumn("dbo.Factories", "PhoneNumber", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "FaxNumber", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "Email", c => c.String(maxLength: 50));
            AddColumn("dbo.Factories", "ContactName", c => c.String(maxLength: 10));
            AddColumn("dbo.Factories", "ContactTiitle", c => c.String(maxLength: 16));
            AddColumn("dbo.Factories", "TelephoneNumber", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "MobileNumber", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "ContactEmail", c => c.String(maxLength: 50));
            AddColumn("dbo.Factories", "CloseDate", c => c.Short(nullable: false));
            AddColumn("dbo.Factories", "PayDate", c => c.Short(nullable: false));
            AddColumn("dbo.Factories", "PayDays", c => c.Short(nullable: false));
            AddColumn("dbo.Factories", "TaxID", c => c.String(maxLength: 8));
            AddColumn("dbo.Factories", "Site", c => c.String(maxLength: 150));
            AddColumn("dbo.Factories", "FactoryLevel", c => c.String(maxLength: 3));
            AddColumn("dbo.Factories", "FactoryType", c => c.String(maxLength: 10));
            AddColumn("dbo.Factories", "Account1", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "Account2", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "PayTerms", c => c.String(maxLength: 30));
            AddColumn("dbo.Factories", "PayCode", c => c.String(maxLength: 1));
            AddColumn("dbo.Factories", "Memo", c => c.String(maxLength: 120));
            AddColumn("dbo.Factories", "InValidDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Factories", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Factories", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Factories", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Factories", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.LongOrder_m", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.LongOrder_m", "LongOrderNo", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.LongOrder_m", "OrderNo", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.LongOrder_m", "DatetimeS", c => c.DateTime(nullable: false));
            AddColumn("dbo.LongOrder_m", "DatetimeE", c => c.DateTime(nullable: false));
            AddColumn("dbo.LongOrder_m", "CycleDay", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.LongOrder_m", "CycleWeek", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.LongOrder_m", "CycleMonth", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.LongOrder_m", "CycleHour", c => c.DateTime(nullable: false));
            AddColumn("dbo.LongOrder_m", "Memo", c => c.String());
            AddColumn("dbo.LongOrder_m", "DataStatus", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.LongOrder_m", "CreateUserID", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.LongOrder_m", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.LongOrder_m", "ModifyUserID", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.LongOrder_m", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_d", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Order_d", "OrderNo", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_d", "OrderSeq", c => c.String(nullable: false, maxLength: 3));
            AddColumn("dbo.Order_d", "QuoteNo", c => c.String(maxLength: 20));
            AddColumn("dbo.Order_d", "QuoteSeq", c => c.String(maxLength: 3));
            AddColumn("dbo.Order_d", "ProductID", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.Order_d", "ProdName", c => c.String(maxLength: 40));
            AddColumn("dbo.Order_d", "ProdSpec", c => c.String());
            AddColumn("dbo.Order_d", "ProdUnit", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Order_d", "CostPrice", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Order_d", "UnitPrice", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Order_d", "Discount", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Order_d", "Memo", c => c.String());
            AddColumn("dbo.Order_d", "OrderStatus", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Order_d", "DataStatus", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Order_d", "EndCode_YN", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Order_d", "CreateUserID", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_d", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_d", "ModifyUserID", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_d", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_m", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Order_m", "OrderNo", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_m", "OrderDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_m", "CustomerID", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Order_m", "CustName", c => c.String(maxLength: 40));
            AddColumn("dbo.Order_m", "FaxNumber", c => c.String(maxLength: 15));
            AddColumn("dbo.Order_m", "ContactName", c => c.String(maxLength: 20));
            AddColumn("dbo.Order_m", "TelephoneNumber", c => c.String(maxLength: 15));
            AddColumn("dbo.Order_m", "MobileNumber", c => c.String(maxLength: 15));
            AddColumn("dbo.Order_m", "Email", c => c.String(maxLength: 50));
            AddColumn("dbo.Order_m", "PayKind", c => c.String(nullable: false, maxLength: 3));
            AddColumn("dbo.Order_m", "DeliveryAddress", c => c.String(maxLength: 150));
            AddColumn("dbo.Order_m", "CheckUserID", c => c.String(maxLength: 20));
            AddColumn("dbo.Order_m", "PayAccount", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_m", "AppleyAccount", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Order_m", "AccountNAME", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_m", "Memo", c => c.String());
            AddColumn("dbo.Order_m", "DataStatus", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Order_m", "DeliveryDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_m", "DeliveryUserID", c => c.String(maxLength: 20));
            AddColumn("dbo.Order_m", "CreateUserID", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_m", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_m", "ModifyUserID", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_m", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Params", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Params", "ParaKind", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Params", "ParaName", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Params", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Params", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Params", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Params", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Privileges", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Privileges", "GroupID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Privileges", "ProgramID", c => c.String(nullable: false, maxLength: 15));
            AddColumn("dbo.Privileges", "Add", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "Search", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "Modify", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "Delete", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "Print", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "Run", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "Help", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "Transform", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Privileges", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Privileges", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Privileges", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ProductKinds", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.ProductKinds", "ProdKind", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.ProductKinds", "ProdKindName", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.ProductKinds", "ParentProdKind", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.ProductKinds", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.ProductKinds", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ProductKinds", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.ProductKinds", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Products", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Products", "ProductID", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.Products", "ProdKind", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Products", "BarCode", c => c.String(maxLength: 40));
            AddColumn("dbo.Products", "ProdName", c => c.String(nullable: false, maxLength: 40));
            AddColumn("dbo.Products", "ProdSpec", c => c.String());
            AddColumn("dbo.Products", "ProdColor", c => c.String(maxLength: 10));
            AddColumn("dbo.Products", "ProdUnit", c => c.String(maxLength: 10));
            AddColumn("dbo.Products", "ProdPhoto", c => c.String());
            AddColumn("dbo.Products", "New_YN", c => c.String(maxLength: 1));
            AddColumn("dbo.Products", "ProdOrigin", c => c.String(maxLength: 100));
            AddColumn("dbo.Products", "ProdSubject", c => c.String());
            AddColumn("dbo.Products", "FactoryID", c => c.String(maxLength: 10));
            AddColumn("dbo.Products", "FinalPrice", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "AvegPrice", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "CostPrice", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "SalePrice", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "WarehouseID", c => c.String(maxLength: 20));
            AddColumn("dbo.Products", "BarCode_YN", c => c.String(maxLength: 1));
            AddColumn("dbo.Products", "CheckStock_YN", c => c.String(maxLength: 1));
            AddColumn("dbo.Products", "StockIO_YN", c => c.String(maxLength: 1));
            AddColumn("dbo.Products", "SafeQty", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "DataStatus", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Products", "Memo", c => c.String(maxLength: 100));
            AddColumn("dbo.Products", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Products", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Products", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Products", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Programs", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Programs", "ProgramID", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Programs", "ParentProgramID", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Programs", "ProgDescription", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Programs", "Add", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "Search", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "Modify", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "Delete", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "Print", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "Run", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "Help", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "Transform", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "Memo", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.Programs", "ProgramOrder", c => c.Int(nullable: false));
            AddColumn("dbo.Programs", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Programs", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Programs", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Programs", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Stocks", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Stocks", "WarehouseID", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Stocks", "ProductID", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.Stocks", "BatNo", c => c.String(nullable: false, maxLength: 25));
            AddColumn("dbo.Stocks", "InitQty", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Stocks", "StockQty", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Stocks", "LastTranDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Stocks", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Stocks", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Stocks", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Stocks", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.UserGroup_d", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.UserGroup_d", "GroupID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_d", "UserID", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.UserGroup_d", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_d", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.UserGroup_d", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_d", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.UserGroup_m", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.UserGroup_m", "GroupID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_m", "GroupDOC", c => c.String(nullable: false, maxLength: 40));
            AddColumn("dbo.UserGroup_m", "Memo", c => c.String(maxLength: 60));
            AddColumn("dbo.UserGroup_m", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_m", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.UserGroup_m", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_m", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Users", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Users", "UserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Users", "UserPassword", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Users", "EmpID", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Users", "Email", c => c.String(maxLength: 50));
            AddColumn("dbo.Users", "Memo", c => c.String(maxLength: 30));
            AddColumn("dbo.Users", "InValidDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.Users", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Users", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Users", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Users", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Warehouses", "CompanyID", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Warehouses", "WarehouseID", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Warehouses", "WarehouseName", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Warehouses", "PhoneNumber", c => c.String(maxLength: 20));
            AddColumn("dbo.Warehouses", "WarehouseAddress", c => c.String(maxLength: 150));
            AddColumn("dbo.Warehouses", "CreateUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Warehouses", "CreateDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Warehouses", "ModifyUserID", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Warehouses", "ModifyDateTime", c => c.DateTime(nullable: false));
            AddPrimaryKey("dbo.CodeKinds", new[] { "CompanyID", "Code_Kind" });
            AddPrimaryKey("dbo.Codes", new[] { "CompanyID", "Code_Kind", "CodeID" });
            AddPrimaryKey("dbo.CombProduct_d", new[] { "CompanyID", "CombProductID", "CombProdSeq" });
            AddPrimaryKey("dbo.CombProduct_m", new[] { "CompanyID", "CombProductID" });
            AddPrimaryKey("dbo.Companies", "CompanyID");
            AddPrimaryKey("dbo.Factories", new[] { "CompanyID", "FactoryID" });
            AddPrimaryKey("dbo.LongOrder_m", new[] { "CompanyID", "LongOrderNo" });
            AddPrimaryKey("dbo.Order_d", new[] { "CompanyID", "OrderNo", "OrderSeq" });
            AddPrimaryKey("dbo.Order_m", new[] { "CompanyID", "OrderNo" });
            AddPrimaryKey("dbo.Params", new[] { "CompanyID", "ParaKind", "Para1" });
            AddPrimaryKey("dbo.Privileges", new[] { "CompanyID", "GroupID", "ProgramID" });
            AddPrimaryKey("dbo.ProductKinds", new[] { "CompanyID", "ProdKind" });
            AddPrimaryKey("dbo.Products", new[] { "CompanyID", "ProductID" });
            AddPrimaryKey("dbo.Programs", new[] { "CompanyID", "ProgramID" });
            AddPrimaryKey("dbo.Stocks", new[] { "CompanyID", "WarehouseID", "ProductID", "BatNo" });
            AddPrimaryKey("dbo.UserGroup_d", new[] { "CompanyID", "GroupID", "UserID" });
            AddPrimaryKey("dbo.UserGroup_m", new[] { "CompanyID", "GroupID" });
            AddPrimaryKey("dbo.Users", new[] { "CompanyID", "UserID" });
            AddPrimaryKey("dbo.Warehouses", new[] { "CompanyID", "WarehouseID" });
            DropColumn("dbo.CodeKinds", "company_no");
            DropColumn("dbo.CodeKinds", "code_kind_name");
            DropColumn("dbo.CodeKinds", "create_user_id");
            DropColumn("dbo.CodeKinds", "create_datetime");
            DropColumn("dbo.CodeKinds", "modify_user_id");
            DropColumn("dbo.CodeKinds", "modify_datetime");
            DropColumn("dbo.Codes", "company_no");
            DropColumn("dbo.Codes", "code");
            DropColumn("dbo.Codes", "code_name");
            DropColumn("dbo.Codes", "create_user_id");
            DropColumn("dbo.Codes", "create_datetime");
            DropColumn("dbo.Codes", "modify_user_id");
            DropColumn("dbo.Codes", "modify_datetime");
            DropColumn("dbo.CombProduct_d", "company_no");
            DropColumn("dbo.CombProduct_d", "CombProd_no");
            DropColumn("dbo.CombProduct_d", "CombProd_seq");
            DropColumn("dbo.CombProduct_d", "Prod_no");
            DropColumn("dbo.CombProduct_d", "Other_Prod_no");
            DropColumn("dbo.CombProduct_d", "create_user_id");
            DropColumn("dbo.CombProduct_d", "create_datetime");
            DropColumn("dbo.CombProduct_d", "modify_user_id");
            DropColumn("dbo.CombProduct_d", "modify_datetime");
            DropColumn("dbo.CombProduct_m", "company_no");
            DropColumn("dbo.CombProduct_m", "CombProd_no");
            DropColumn("dbo.CombProduct_m", "CombProd_name");
            DropColumn("dbo.CombProduct_m", "CombProd_spec");
            DropColumn("dbo.CombProduct_m", "create_user_id");
            DropColumn("dbo.CombProduct_m", "create_datetime");
            DropColumn("dbo.CombProduct_m", "modify_user_id");
            DropColumn("dbo.CombProduct_m", "modify_datetime");
            DropColumn("dbo.Companies", "company_no");
            DropColumn("dbo.Companies", "company_name");
            DropColumn("dbo.Companies", "for_short");
            DropColumn("dbo.Companies", "country_no");
            DropColumn("dbo.Companies", "area_no");
            DropColumn("dbo.Companies", "tel_no");
            DropColumn("dbo.Companies", "fax_no");
            DropColumn("dbo.Companies", "c_addr");
            DropColumn("dbo.Companies", "www_addr");
            DropColumn("dbo.Companies", "email_addr");
            DropColumn("dbo.Companies", "Bis_time_S");
            DropColumn("dbo.Companies", "Bis_time_E");
            DropColumn("dbo.Companies", "create_user_id");
            DropColumn("dbo.Companies", "create_datetime");
            DropColumn("dbo.Companies", "modify_user_id");
            DropColumn("dbo.Companies", "modify_datetime");
            DropColumn("dbo.Factories", "company_no");
            DropColumn("dbo.Factories", "FACT_NO");
            DropColumn("dbo.Factories", "bri_co");
            DropColumn("dbo.Factories", "ef_co");
            DropColumn("dbo.Factories", "post_no");
            DropColumn("dbo.Factories", "c_post_no");
            DropColumn("dbo.Factories", "c_addr");
            DropColumn("dbo.Factories", "p_name");
            DropColumn("dbo.Factories", "country_no");
            DropColumn("dbo.Factories", "area_no");
            DropColumn("dbo.Factories", "tel_no");
            DropColumn("dbo.Factories", "fax_no");
            DropColumn("dbo.Factories", "email_addr");
            DropColumn("dbo.Factories", "c_name");
            DropColumn("dbo.Factories", "c_til_name");
            DropColumn("dbo.Factories", "c_tel_no");
            DropColumn("dbo.Factories", "c_mobile_no");
            DropColumn("dbo.Factories", "c_email_addr");
            DropColumn("dbo.Factories", "cdate");
            DropColumn("dbo.Factories", "pdate");
            DropColumn("dbo.Factories", "Coll_days");
            DropColumn("dbo.Factories", "invo_tax_no");
            DropColumn("dbo.Factories", "www_addr");
            DropColumn("dbo.Factories", "class_kind");
            DropColumn("dbo.Factories", "supp_type");
            DropColumn("dbo.Factories", "account_no1");
            DropColumn("dbo.Factories", "account_no2");
            DropColumn("dbo.Factories", "pay_cond");
            DropColumn("dbo.Factories", "pay_code");
            DropColumn("dbo.Factories", "remarker");
            DropColumn("dbo.Factories", "invalid_date");
            DropColumn("dbo.Factories", "create_user_id");
            DropColumn("dbo.Factories", "create_datetime");
            DropColumn("dbo.Factories", "modify_user_id");
            DropColumn("dbo.Factories", "modify_datetime");
            DropColumn("dbo.LongOrder_m", "company_no");
            DropColumn("dbo.LongOrder_m", "LongOrder_No");
            DropColumn("dbo.LongOrder_m", "Order_No");
            DropColumn("dbo.LongOrder_m", "Del_datetimeS");
            DropColumn("dbo.LongOrder_m", "Del_datetimeE");
            DropColumn("dbo.LongOrder_m", "Del_cycleD");
            DropColumn("dbo.LongOrder_m", "Del_cycleW");
            DropColumn("dbo.LongOrder_m", "Del_cycleM");
            DropColumn("dbo.LongOrder_m", "Del_datetime");
            DropColumn("dbo.LongOrder_m", "remarker");
            DropColumn("dbo.LongOrder_m", "r_status");
            DropColumn("dbo.LongOrder_m", "create_user_id");
            DropColumn("dbo.LongOrder_m", "create_datetime");
            DropColumn("dbo.LongOrder_m", "modify_user_id");
            DropColumn("dbo.LongOrder_m", "modify_datetime");
            DropColumn("dbo.Order_d", "company_no");
            DropColumn("dbo.Order_d", "Order_No");
            DropColumn("dbo.Order_d", "Order_seq");
            DropColumn("dbo.Order_d", "Quote_no");
            DropColumn("dbo.Order_d", "Quote_seq");
            DropColumn("dbo.Order_d", "Prod_No");
            DropColumn("dbo.Order_d", "Prod_name");
            DropColumn("dbo.Order_d", "Prod_spec");
            DropColumn("dbo.Order_d", "Prod_unit");
            DropColumn("dbo.Order_d", "unit_cost");
            DropColumn("dbo.Order_d", "unit_Price");
            DropColumn("dbo.Order_d", "On_slae");
            DropColumn("dbo.Order_d", "remarker");
            DropColumn("dbo.Order_d", "Order_status");
            DropColumn("dbo.Order_d", "r_status");
            DropColumn("dbo.Order_d", "end_code");
            DropColumn("dbo.Order_d", "create_user_id");
            DropColumn("dbo.Order_d", "create_datetime");
            DropColumn("dbo.Order_d", "modify_user_id");
            DropColumn("dbo.Order_d", "modify_datetime");
            DropColumn("dbo.Order_m", "company_no");
            DropColumn("dbo.Order_m", "Order_No");
            DropColumn("dbo.Order_m", "Order_date");
            DropColumn("dbo.Order_m", "cust_no");
            DropColumn("dbo.Order_m", "ef_co");
            DropColumn("dbo.Order_m", "fax_no");
            DropColumn("dbo.Order_m", "c_name");
            DropColumn("dbo.Order_m", "c_tel_no");
            DropColumn("dbo.Order_m", "c_mobile_no");
            DropColumn("dbo.Order_m", "c_email_addr");
            DropColumn("dbo.Order_m", "pay_kind");
            DropColumn("dbo.Order_m", "bill_addr");
            DropColumn("dbo.Order_m", "check_user_id");
            DropColumn("dbo.Order_m", "ACCNO");
            DropColumn("dbo.Order_m", "ACCUNIT");
            DropColumn("dbo.Order_m", "ACCNAME");
            DropColumn("dbo.Order_m", "remarker");
            DropColumn("dbo.Order_m", "r_status");
            DropColumn("dbo.Order_m", "delivery_datetime");
            DropColumn("dbo.Order_m", "delivery_user_id");
            DropColumn("dbo.Order_m", "create_user_id");
            DropColumn("dbo.Order_m", "create_datetime");
            DropColumn("dbo.Order_m", "modify_user_id");
            DropColumn("dbo.Order_m", "modify_datetime");
            DropColumn("dbo.Params", "company_no");
            DropColumn("dbo.Params", "para_kind");
            DropColumn("dbo.Params", "para_name");
            DropColumn("dbo.Params", "create_user_id");
            DropColumn("dbo.Params", "create_datetime");
            DropColumn("dbo.Params", "modify_user_id");
            DropColumn("dbo.Params", "modify_datetime");
            DropColumn("dbo.Privileges", "company_no");
            DropColumn("dbo.Privileges", "user_id");
            DropColumn("dbo.Privileges", "program_id");
            DropColumn("dbo.Privileges", "up_add");
            DropColumn("dbo.Privileges", "up_query");
            DropColumn("dbo.Privileges", "up_modify");
            DropColumn("dbo.Privileges", "up_delete");
            DropColumn("dbo.Privileges", "up_print");
            DropColumn("dbo.Privileges", "up_run");
            DropColumn("dbo.Privileges", "up_help");
            DropColumn("dbo.Privileges", "up_transform");
            DropColumn("dbo.Privileges", "create_user_id");
            DropColumn("dbo.Privileges", "create_datetime");
            DropColumn("dbo.Privileges", "modify_user_id");
            DropColumn("dbo.Privileges", "modify_datetime");
            DropColumn("dbo.ProductKinds", "company_no");
            DropColumn("dbo.ProductKinds", "Prod_kind");
            DropColumn("dbo.ProductKinds", "kind_name");
            DropColumn("dbo.ProductKinds", "parent_kind");
            DropColumn("dbo.ProductKinds", "create_user_id");
            DropColumn("dbo.ProductKinds", "create_datetime");
            DropColumn("dbo.ProductKinds", "modify_user_id");
            DropColumn("dbo.ProductKinds", "modify_datetime");
            DropColumn("dbo.Products", "company_no");
            DropColumn("dbo.Products", "Prod_no");
            DropColumn("dbo.Products", "Prod_kind");
            DropColumn("dbo.Products", "Prod_barcode");
            DropColumn("dbo.Products", "Prod_name");
            DropColumn("dbo.Products", "Prod_spec");
            DropColumn("dbo.Products", "Prod_color");
            DropColumn("dbo.Products", "Prod_unit");
            DropColumn("dbo.Products", "Prod_photo");
            DropColumn("dbo.Products", "other_spec4");
            DropColumn("dbo.Products", "other_spec5");
            DropColumn("dbo.Products", "prod_subject");
            DropColumn("dbo.Products", "FACT_NO");
            DropColumn("dbo.Products", "Last_Price");
            DropColumn("dbo.Products", "Aveg_Price");
            DropColumn("dbo.Products", "Unit_Price");
            DropColumn("dbo.Products", "sale_Price");
            DropColumn("dbo.Products", "warehouse_no");
            DropColumn("dbo.Products", "no_barcode");
            DropColumn("dbo.Products", "stk_yn");
            DropColumn("dbo.Products", "stk_io_yn");
            DropColumn("dbo.Products", "safe_qty");
            DropColumn("dbo.Products", "r_status");
            DropColumn("dbo.Products", "temperature");
            DropColumn("dbo.Products", "sugar");
            DropColumn("dbo.Products", "size");
            DropColumn("dbo.Products", "memo_doc");
            DropColumn("dbo.Products", "create_user_id");
            DropColumn("dbo.Products", "create_datetime");
            DropColumn("dbo.Products", "modify_user_id");
            DropColumn("dbo.Products", "modify_datetime");
            DropColumn("dbo.Programs", "company_no");
            DropColumn("dbo.Programs", "program_id");
            DropColumn("dbo.Programs", "parent_program_id");
            DropColumn("dbo.Programs", "prog_description");
            DropColumn("dbo.Programs", "up_add");
            DropColumn("dbo.Programs", "up_query");
            DropColumn("dbo.Programs", "up_modify");
            DropColumn("dbo.Programs", "up_delete");
            DropColumn("dbo.Programs", "up_print");
            DropColumn("dbo.Programs", "up_run");
            DropColumn("dbo.Programs", "up_help");
            DropColumn("dbo.Programs", "up_transform");
            DropColumn("dbo.Programs", "prog_memo");
            DropColumn("dbo.Programs", "program_order");
            DropColumn("dbo.Programs", "create_user_id");
            DropColumn("dbo.Programs", "create_datetime");
            DropColumn("dbo.Programs", "modify_user_id");
            DropColumn("dbo.Programs", "modify_datetime");
            DropColumn("dbo.Stocks", "company_no");
            DropColumn("dbo.Stocks", "warehouse_no");
            DropColumn("dbo.Stocks", "Prod_no");
            DropColumn("dbo.Stocks", "Bat_no");
            DropColumn("dbo.Stocks", "init_qty");
            DropColumn("dbo.Stocks", "stock_qty");
            DropColumn("dbo.Stocks", "last_tran_date");
            DropColumn("dbo.Stocks", "create_user_id");
            DropColumn("dbo.Stocks", "create_datetime");
            DropColumn("dbo.Stocks", "modify_user_id");
            DropColumn("dbo.Stocks", "modify_datetime");
            DropColumn("dbo.UserGroup_d", "company_no");
            DropColumn("dbo.UserGroup_d", "group_id");
            DropColumn("dbo.UserGroup_d", "user_id");
            DropColumn("dbo.UserGroup_d", "create_user_id");
            DropColumn("dbo.UserGroup_d", "create_datetime");
            DropColumn("dbo.UserGroup_d", "modify_user_id");
            DropColumn("dbo.UserGroup_d", "modify_datetime");
            DropColumn("dbo.UserGroup_m", "company_no");
            DropColumn("dbo.UserGroup_m", "group_id");
            DropColumn("dbo.UserGroup_m", "group_doc");
            DropColumn("dbo.UserGroup_m", "program_used");
            DropColumn("dbo.UserGroup_m", "create_user_id");
            DropColumn("dbo.UserGroup_m", "create_datetime");
            DropColumn("dbo.UserGroup_m", "modify_user_id");
            DropColumn("dbo.UserGroup_m", "modify_datetime");
            DropColumn("dbo.Users", "company_no");
            DropColumn("dbo.Users", "user_id");
            DropColumn("dbo.Users", "user_password");
            DropColumn("dbo.Users", "emp_no");
            DropColumn("dbo.Users", "email_addr");
            DropColumn("dbo.Users", "memo_doc");
            DropColumn("dbo.Users", "invalid_date");
            DropColumn("dbo.Users", "create_user_id");
            DropColumn("dbo.Users", "create_datetime");
            DropColumn("dbo.Users", "modify_user_id");
            DropColumn("dbo.Users", "modify_datetime");
            DropColumn("dbo.Warehouses", "company_no");
            DropColumn("dbo.Warehouses", "warehouse_no");
            DropColumn("dbo.Warehouses", "warehouse_name");
            DropColumn("dbo.Warehouses", "tel_no");
            DropColumn("dbo.Warehouses", "w_addr");
            DropColumn("dbo.Warehouses", "create_user_id");
            DropColumn("dbo.Warehouses", "create_datetime");
            DropColumn("dbo.Warehouses", "modify_user_id");
            DropColumn("dbo.Warehouses", "modify_datetime");
            DropTable("dbo.Custs");
        }
        
        public override void Down()
        {
            CreateTable(
                "dbo.Custs",
                c => new
                    {
                        cust_no = c.String(nullable: false, maxLength: 16),
                        ef_co = c.String(nullable: false, maxLength: 40),
                        cust_password = c.String(nullable: false, maxLength: 20),
                        bri_co = c.String(nullable: false, maxLength: 12),
                        sex_type = c.String(nullable: false, maxLength: 1),
                        cust_class = c.String(maxLength: 10),
                        cust_type = c.String(maxLength: 10),
                        c_name = c.String(maxLength: 20),
                        c_tel_no = c.String(maxLength: 15),
                        c_mobile_no = c.String(maxLength: 15),
                        c_email_addr = c.String(maxLength: 50),
                        c_email_Ver = c.String(maxLength: 1),
                        invo_tax_no = c.String(maxLength: 10),
                        b_post_no = c.String(maxLength: 6),
                        b_addr = c.String(maxLength: 150),
                        b_post_no2 = c.String(maxLength: 6),
                        b_addr2 = c.String(maxLength: 150),
                        remarker = c.String(maxLength: 120),
                        valid_date = c.DateTime(nullable: false),
                        invalid_date = c.DateTime(nullable: false),
                        Stored_Point = c.Int(nullable: false),
                        birthday = c.DateTime(nullable: false),
                        job = c.String(maxLength: 3),
                        create_user_id = c.String(nullable: false, maxLength: 14),
                        create_datetime = c.DateTime(nullable: false),
                        modify_user_id = c.String(nullable: false, maxLength: 14),
                        modify_datetime = c.DateTime(nullable: false),
                    })
                .PrimaryKey(t => t.cust_no);
            
            AddColumn("dbo.Warehouses", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Warehouses", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Warehouses", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Warehouses", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Warehouses", "w_addr", c => c.String(maxLength: 150));
            AddColumn("dbo.Warehouses", "tel_no", c => c.String(maxLength: 20));
            AddColumn("dbo.Warehouses", "warehouse_name", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Warehouses", "warehouse_no", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Warehouses", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Users", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Users", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Users", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Users", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Users", "invalid_date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Users", "memo_doc", c => c.String(maxLength: 30));
            AddColumn("dbo.Users", "email_addr", c => c.String(maxLength: 50));
            AddColumn("dbo.Users", "emp_no", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Users", "user_password", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Users", "user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Users", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.UserGroup_m", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.UserGroup_m", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_m", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.UserGroup_m", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_m", "program_used", c => c.String(maxLength: 60));
            AddColumn("dbo.UserGroup_m", "group_doc", c => c.String(nullable: false, maxLength: 40));
            AddColumn("dbo.UserGroup_m", "group_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_m", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.UserGroup_d", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.UserGroup_d", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_d", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.UserGroup_d", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_d", "user_id", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.UserGroup_d", "group_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.UserGroup_d", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Stocks", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Stocks", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Stocks", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Stocks", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Stocks", "last_tran_date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Stocks", "stock_qty", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Stocks", "init_qty", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Stocks", "Bat_no", c => c.String(nullable: false, maxLength: 25));
            AddColumn("dbo.Stocks", "Prod_no", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.Stocks", "warehouse_no", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Stocks", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Programs", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Programs", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Programs", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Programs", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Programs", "program_order", c => c.Int(nullable: false));
            AddColumn("dbo.Programs", "prog_memo", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.Programs", "up_transform", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "up_help", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "up_run", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "up_print", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "up_delete", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "up_modify", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "up_query", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "up_add", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Programs", "prog_description", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Programs", "parent_program_id", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Programs", "program_id", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Programs", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Products", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Products", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Products", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Products", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Products", "memo_doc", c => c.String(maxLength: 100));
            AddColumn("dbo.Products", "size", c => c.String(maxLength: 3));
            AddColumn("dbo.Products", "sugar", c => c.String(maxLength: 3));
            AddColumn("dbo.Products", "temperature", c => c.String(maxLength: 3));
            AddColumn("dbo.Products", "r_status", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Products", "safe_qty", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "stk_io_yn", c => c.String(maxLength: 1));
            AddColumn("dbo.Products", "stk_yn", c => c.String(maxLength: 1));
            AddColumn("dbo.Products", "no_barcode", c => c.String(maxLength: 1));
            AddColumn("dbo.Products", "warehouse_no", c => c.String(maxLength: 20));
            AddColumn("dbo.Products", "sale_Price", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "Unit_Price", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "Aveg_Price", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "Last_Price", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Products", "FACT_NO", c => c.String(maxLength: 10));
            AddColumn("dbo.Products", "prod_subject", c => c.String());
            AddColumn("dbo.Products", "other_spec5", c => c.String(maxLength: 100));
            AddColumn("dbo.Products", "other_spec4", c => c.String(maxLength: 1));
            AddColumn("dbo.Products", "Prod_photo", c => c.String());
            AddColumn("dbo.Products", "Prod_unit", c => c.String(maxLength: 10));
            AddColumn("dbo.Products", "Prod_color", c => c.String(maxLength: 10));
            AddColumn("dbo.Products", "Prod_spec", c => c.String());
            AddColumn("dbo.Products", "Prod_name", c => c.String(nullable: false, maxLength: 40));
            AddColumn("dbo.Products", "Prod_barcode", c => c.String(maxLength: 40));
            AddColumn("dbo.Products", "Prod_kind", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Products", "Prod_no", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.Products", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.ProductKinds", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ProductKinds", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.ProductKinds", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ProductKinds", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.ProductKinds", "parent_kind", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.ProductKinds", "kind_name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.ProductKinds", "Prod_kind", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.ProductKinds", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Privileges", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Privileges", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Privileges", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Privileges", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Privileges", "up_transform", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "up_help", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "up_run", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "up_print", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "up_delete", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "up_modify", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "up_query", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "up_add", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Privileges", "program_id", c => c.String(nullable: false, maxLength: 15));
            AddColumn("dbo.Privileges", "user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Privileges", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Params", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Params", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Params", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Params", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Params", "para_name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.Params", "para_kind", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Params", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Order_m", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_m", "modify_user_id", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_m", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_m", "create_user_id", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_m", "delivery_user_id", c => c.String(maxLength: 20));
            AddColumn("dbo.Order_m", "delivery_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_m", "r_status", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Order_m", "remarker", c => c.String());
            AddColumn("dbo.Order_m", "ACCNAME", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_m", "ACCUNIT", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Order_m", "ACCNO", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_m", "check_user_id", c => c.String(maxLength: 20));
            AddColumn("dbo.Order_m", "bill_addr", c => c.String(maxLength: 150));
            AddColumn("dbo.Order_m", "pay_kind", c => c.String(nullable: false, maxLength: 3));
            AddColumn("dbo.Order_m", "c_email_addr", c => c.String(maxLength: 50));
            AddColumn("dbo.Order_m", "c_mobile_no", c => c.String(maxLength: 15));
            AddColumn("dbo.Order_m", "c_tel_no", c => c.String(maxLength: 15));
            AddColumn("dbo.Order_m", "c_name", c => c.String(maxLength: 20));
            AddColumn("dbo.Order_m", "fax_no", c => c.String(maxLength: 15));
            AddColumn("dbo.Order_m", "ef_co", c => c.String(maxLength: 40));
            AddColumn("dbo.Order_m", "cust_no", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Order_m", "Order_date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_m", "Order_No", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_m", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Order_d", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_d", "modify_user_id", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_d", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Order_d", "create_user_id", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_d", "end_code", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Order_d", "r_status", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Order_d", "Order_status", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.Order_d", "remarker", c => c.String());
            AddColumn("dbo.Order_d", "On_slae", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Order_d", "unit_Price", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Order_d", "unit_cost", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Order_d", "Prod_unit", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Order_d", "Prod_spec", c => c.String());
            AddColumn("dbo.Order_d", "Prod_name", c => c.String(maxLength: 40));
            AddColumn("dbo.Order_d", "Prod_No", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.Order_d", "Quote_seq", c => c.String(maxLength: 3));
            AddColumn("dbo.Order_d", "Quote_no", c => c.String(maxLength: 20));
            AddColumn("dbo.Order_d", "Order_seq", c => c.String(nullable: false, maxLength: 3));
            AddColumn("dbo.Order_d", "Order_No", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Order_d", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.LongOrder_m", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.LongOrder_m", "modify_user_id", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.LongOrder_m", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.LongOrder_m", "create_user_id", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.LongOrder_m", "r_status", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.LongOrder_m", "remarker", c => c.String());
            AddColumn("dbo.LongOrder_m", "Del_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.LongOrder_m", "Del_cycleM", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.LongOrder_m", "Del_cycleW", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.LongOrder_m", "Del_cycleD", c => c.String(nullable: false, maxLength: 1));
            AddColumn("dbo.LongOrder_m", "Del_datetimeE", c => c.DateTime(nullable: false));
            AddColumn("dbo.LongOrder_m", "Del_datetimeS", c => c.DateTime(nullable: false));
            AddColumn("dbo.LongOrder_m", "Order_No", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.LongOrder_m", "LongOrder_No", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.LongOrder_m", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Factories", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Factories", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Factories", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Factories", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Factories", "invalid_date", c => c.DateTime(nullable: false));
            AddColumn("dbo.Factories", "remarker", c => c.String(maxLength: 120));
            AddColumn("dbo.Factories", "pay_code", c => c.String(maxLength: 1));
            AddColumn("dbo.Factories", "pay_cond", c => c.String(maxLength: 30));
            AddColumn("dbo.Factories", "account_no2", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "account_no1", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "supp_type", c => c.String(maxLength: 10));
            AddColumn("dbo.Factories", "class_kind", c => c.String(maxLength: 3));
            AddColumn("dbo.Factories", "www_addr", c => c.String(maxLength: 150));
            AddColumn("dbo.Factories", "invo_tax_no", c => c.String(maxLength: 8));
            AddColumn("dbo.Factories", "Coll_days", c => c.Short(nullable: false));
            AddColumn("dbo.Factories", "pdate", c => c.Short(nullable: false));
            AddColumn("dbo.Factories", "cdate", c => c.Short(nullable: false));
            AddColumn("dbo.Factories", "c_email_addr", c => c.String(maxLength: 50));
            AddColumn("dbo.Factories", "c_mobile_no", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "c_tel_no", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "c_til_name", c => c.String(maxLength: 16));
            AddColumn("dbo.Factories", "c_name", c => c.String(maxLength: 10));
            AddColumn("dbo.Factories", "email_addr", c => c.String(maxLength: 50));
            AddColumn("dbo.Factories", "fax_no", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "tel_no", c => c.String(maxLength: 15));
            AddColumn("dbo.Factories", "area_no", c => c.String(maxLength: 4));
            AddColumn("dbo.Factories", "country_no", c => c.String(maxLength: 3));
            AddColumn("dbo.Factories", "p_name", c => c.String(maxLength: 10));
            AddColumn("dbo.Factories", "c_addr", c => c.String(maxLength: 150));
            AddColumn("dbo.Factories", "c_post_no", c => c.String(maxLength: 6));
            AddColumn("dbo.Factories", "post_no", c => c.String(maxLength: 6));
            AddColumn("dbo.Factories", "ef_co", c => c.String(nullable: false, maxLength: 40));
            AddColumn("dbo.Factories", "bri_co", c => c.String(nullable: false, maxLength: 10));
            AddColumn("dbo.Factories", "FACT_NO", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.Factories", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Companies", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Companies", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Companies", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Companies", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Companies", "Bis_time_E", c => c.String(maxLength: 5));
            AddColumn("dbo.Companies", "Bis_time_S", c => c.String(maxLength: 5));
            AddColumn("dbo.Companies", "email_addr", c => c.String(maxLength: 50));
            AddColumn("dbo.Companies", "www_addr", c => c.String(maxLength: 150));
            AddColumn("dbo.Companies", "c_addr", c => c.String(maxLength: 150));
            AddColumn("dbo.Companies", "fax_no", c => c.String(maxLength: 15));
            AddColumn("dbo.Companies", "tel_no", c => c.String(maxLength: 15));
            AddColumn("dbo.Companies", "area_no", c => c.String(maxLength: 1));
            AddColumn("dbo.Companies", "country_no", c => c.String(maxLength: 3));
            AddColumn("dbo.Companies", "for_short", c => c.String(nullable: false, maxLength: 20));
            AddColumn("dbo.Companies", "company_name", c => c.String(nullable: false, maxLength: 40));
            AddColumn("dbo.Companies", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.CombProduct_m", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CombProduct_m", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CombProduct_m", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CombProduct_m", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CombProduct_m", "CombProd_spec", c => c.String(nullable: false));
            AddColumn("dbo.CombProduct_m", "CombProd_name", c => c.String(nullable: false, maxLength: 50));
            AddColumn("dbo.CombProduct_m", "CombProd_no", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.CombProduct_m", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.CombProduct_d", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CombProduct_d", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CombProduct_d", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CombProduct_d", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CombProduct_d", "Other_Prod_no", c => c.String(maxLength: 1));
            AddColumn("dbo.CombProduct_d", "Prod_no", c => c.String(maxLength: 16));
            AddColumn("dbo.CombProduct_d", "CombProd_seq", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.CombProduct_d", "CombProd_no", c => c.String(nullable: false, maxLength: 16));
            AddColumn("dbo.CombProduct_d", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.Codes", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Codes", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Codes", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.Codes", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Codes", "code_name", c => c.String(maxLength: 50));
            AddColumn("dbo.Codes", "code", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.Codes", "company_no", c => c.String(nullable: false, maxLength: 6));
            AddColumn("dbo.CodeKinds", "modify_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CodeKinds", "modify_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CodeKinds", "create_datetime", c => c.DateTime(nullable: false));
            AddColumn("dbo.CodeKinds", "create_user_id", c => c.String(nullable: false, maxLength: 14));
            AddColumn("dbo.CodeKinds", "code_kind_name", c => c.String(nullable: false, maxLength: 30));
            AddColumn("dbo.CodeKinds", "company_no", c => c.String(nullable: false, maxLength: 6));
            DropPrimaryKey("dbo.Warehouses");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.UserGroup_m");
            DropPrimaryKey("dbo.UserGroup_d");
            DropPrimaryKey("dbo.Stocks");
            DropPrimaryKey("dbo.Programs");
            DropPrimaryKey("dbo.Products");
            DropPrimaryKey("dbo.ProductKinds");
            DropPrimaryKey("dbo.Privileges");
            DropPrimaryKey("dbo.Params");
            DropPrimaryKey("dbo.Order_m");
            DropPrimaryKey("dbo.Order_d");
            DropPrimaryKey("dbo.LongOrder_m");
            DropPrimaryKey("dbo.Factories");
            DropPrimaryKey("dbo.Companies");
            DropPrimaryKey("dbo.CombProduct_m");
            DropPrimaryKey("dbo.CombProduct_d");
            DropPrimaryKey("dbo.Codes");
            DropPrimaryKey("dbo.CodeKinds");
            DropColumn("dbo.Warehouses", "ModifyDateTime");
            DropColumn("dbo.Warehouses", "ModifyUserID");
            DropColumn("dbo.Warehouses", "CreateDateTime");
            DropColumn("dbo.Warehouses", "CreateUserID");
            DropColumn("dbo.Warehouses", "WarehouseAddress");
            DropColumn("dbo.Warehouses", "PhoneNumber");
            DropColumn("dbo.Warehouses", "WarehouseName");
            DropColumn("dbo.Warehouses", "WarehouseID");
            DropColumn("dbo.Warehouses", "CompanyID");
            DropColumn("dbo.Users", "ModifyDateTime");
            DropColumn("dbo.Users", "ModifyUserID");
            DropColumn("dbo.Users", "CreateDateTime");
            DropColumn("dbo.Users", "CreateUserID");
            DropColumn("dbo.Users", "InValidDate");
            DropColumn("dbo.Users", "Memo");
            DropColumn("dbo.Users", "Email");
            DropColumn("dbo.Users", "EmpID");
            DropColumn("dbo.Users", "UserPassword");
            DropColumn("dbo.Users", "UserID");
            DropColumn("dbo.Users", "CompanyID");
            DropColumn("dbo.UserGroup_m", "ModifyDateTime");
            DropColumn("dbo.UserGroup_m", "ModifyUserID");
            DropColumn("dbo.UserGroup_m", "CreateDateTime");
            DropColumn("dbo.UserGroup_m", "CreateUserID");
            DropColumn("dbo.UserGroup_m", "Memo");
            DropColumn("dbo.UserGroup_m", "GroupDOC");
            DropColumn("dbo.UserGroup_m", "GroupID");
            DropColumn("dbo.UserGroup_m", "CompanyID");
            DropColumn("dbo.UserGroup_d", "ModifyDateTime");
            DropColumn("dbo.UserGroup_d", "ModifyUserID");
            DropColumn("dbo.UserGroup_d", "CreateDateTime");
            DropColumn("dbo.UserGroup_d", "CreateUserID");
            DropColumn("dbo.UserGroup_d", "UserID");
            DropColumn("dbo.UserGroup_d", "GroupID");
            DropColumn("dbo.UserGroup_d", "CompanyID");
            DropColumn("dbo.Stocks", "ModifyDateTime");
            DropColumn("dbo.Stocks", "ModifyUserID");
            DropColumn("dbo.Stocks", "CreateDateTime");
            DropColumn("dbo.Stocks", "CreateUserID");
            DropColumn("dbo.Stocks", "LastTranDate");
            DropColumn("dbo.Stocks", "StockQty");
            DropColumn("dbo.Stocks", "InitQty");
            DropColumn("dbo.Stocks", "BatNo");
            DropColumn("dbo.Stocks", "ProductID");
            DropColumn("dbo.Stocks", "WarehouseID");
            DropColumn("dbo.Stocks", "CompanyID");
            DropColumn("dbo.Programs", "ModifyDateTime");
            DropColumn("dbo.Programs", "ModifyUserID");
            DropColumn("dbo.Programs", "CreateDateTime");
            DropColumn("dbo.Programs", "CreateUserID");
            DropColumn("dbo.Programs", "ProgramOrder");
            DropColumn("dbo.Programs", "Memo");
            DropColumn("dbo.Programs", "Transform");
            DropColumn("dbo.Programs", "Help");
            DropColumn("dbo.Programs", "Run");
            DropColumn("dbo.Programs", "Print");
            DropColumn("dbo.Programs", "Delete");
            DropColumn("dbo.Programs", "Modify");
            DropColumn("dbo.Programs", "Search");
            DropColumn("dbo.Programs", "Add");
            DropColumn("dbo.Programs", "ProgDescription");
            DropColumn("dbo.Programs", "ParentProgramID");
            DropColumn("dbo.Programs", "ProgramID");
            DropColumn("dbo.Programs", "CompanyID");
            DropColumn("dbo.Products", "ModifyDateTime");
            DropColumn("dbo.Products", "ModifyUserID");
            DropColumn("dbo.Products", "CreateDateTime");
            DropColumn("dbo.Products", "CreateUserID");
            DropColumn("dbo.Products", "Memo");
            DropColumn("dbo.Products", "DataStatus");
            DropColumn("dbo.Products", "SafeQty");
            DropColumn("dbo.Products", "StockIO_YN");
            DropColumn("dbo.Products", "CheckStock_YN");
            DropColumn("dbo.Products", "BarCode_YN");
            DropColumn("dbo.Products", "WarehouseID");
            DropColumn("dbo.Products", "SalePrice");
            DropColumn("dbo.Products", "CostPrice");
            DropColumn("dbo.Products", "AvegPrice");
            DropColumn("dbo.Products", "FinalPrice");
            DropColumn("dbo.Products", "FactoryID");
            DropColumn("dbo.Products", "ProdSubject");
            DropColumn("dbo.Products", "ProdOrigin");
            DropColumn("dbo.Products", "New_YN");
            DropColumn("dbo.Products", "ProdPhoto");
            DropColumn("dbo.Products", "ProdUnit");
            DropColumn("dbo.Products", "ProdColor");
            DropColumn("dbo.Products", "ProdSpec");
            DropColumn("dbo.Products", "ProdName");
            DropColumn("dbo.Products", "BarCode");
            DropColumn("dbo.Products", "ProdKind");
            DropColumn("dbo.Products", "ProductID");
            DropColumn("dbo.Products", "CompanyID");
            DropColumn("dbo.ProductKinds", "ModifyDateTime");
            DropColumn("dbo.ProductKinds", "ModifyUserID");
            DropColumn("dbo.ProductKinds", "CreateDateTime");
            DropColumn("dbo.ProductKinds", "CreateUserID");
            DropColumn("dbo.ProductKinds", "ParentProdKind");
            DropColumn("dbo.ProductKinds", "ProdKindName");
            DropColumn("dbo.ProductKinds", "ProdKind");
            DropColumn("dbo.ProductKinds", "CompanyID");
            DropColumn("dbo.Privileges", "ModifyDateTime");
            DropColumn("dbo.Privileges", "ModifyUserID");
            DropColumn("dbo.Privileges", "CreateDateTime");
            DropColumn("dbo.Privileges", "CreateUserID");
            DropColumn("dbo.Privileges", "Transform");
            DropColumn("dbo.Privileges", "Help");
            DropColumn("dbo.Privileges", "Run");
            DropColumn("dbo.Privileges", "Print");
            DropColumn("dbo.Privileges", "Delete");
            DropColumn("dbo.Privileges", "Modify");
            DropColumn("dbo.Privileges", "Search");
            DropColumn("dbo.Privileges", "Add");
            DropColumn("dbo.Privileges", "ProgramID");
            DropColumn("dbo.Privileges", "GroupID");
            DropColumn("dbo.Privileges", "CompanyID");
            DropColumn("dbo.Params", "ModifyDateTime");
            DropColumn("dbo.Params", "ModifyUserID");
            DropColumn("dbo.Params", "CreateDateTime");
            DropColumn("dbo.Params", "CreateUserID");
            DropColumn("dbo.Params", "ParaName");
            DropColumn("dbo.Params", "ParaKind");
            DropColumn("dbo.Params", "CompanyID");
            DropColumn("dbo.Order_m", "ModifyDateTime");
            DropColumn("dbo.Order_m", "ModifyUserID");
            DropColumn("dbo.Order_m", "CreateDateTime");
            DropColumn("dbo.Order_m", "CreateUserID");
            DropColumn("dbo.Order_m", "DeliveryUserID");
            DropColumn("dbo.Order_m", "DeliveryDateTime");
            DropColumn("dbo.Order_m", "DataStatus");
            DropColumn("dbo.Order_m", "Memo");
            DropColumn("dbo.Order_m", "AccountNAME");
            DropColumn("dbo.Order_m", "AppleyAccount");
            DropColumn("dbo.Order_m", "PayAccount");
            DropColumn("dbo.Order_m", "CheckUserID");
            DropColumn("dbo.Order_m", "DeliveryAddress");
            DropColumn("dbo.Order_m", "PayKind");
            DropColumn("dbo.Order_m", "Email");
            DropColumn("dbo.Order_m", "MobileNumber");
            DropColumn("dbo.Order_m", "TelephoneNumber");
            DropColumn("dbo.Order_m", "ContactName");
            DropColumn("dbo.Order_m", "FaxNumber");
            DropColumn("dbo.Order_m", "CustName");
            DropColumn("dbo.Order_m", "CustomerID");
            DropColumn("dbo.Order_m", "OrderDateTime");
            DropColumn("dbo.Order_m", "OrderNo");
            DropColumn("dbo.Order_m", "CompanyID");
            DropColumn("dbo.Order_d", "ModifyDateTime");
            DropColumn("dbo.Order_d", "ModifyUserID");
            DropColumn("dbo.Order_d", "CreateDateTime");
            DropColumn("dbo.Order_d", "CreateUserID");
            DropColumn("dbo.Order_d", "EndCode_YN");
            DropColumn("dbo.Order_d", "DataStatus");
            DropColumn("dbo.Order_d", "OrderStatus");
            DropColumn("dbo.Order_d", "Memo");
            DropColumn("dbo.Order_d", "Discount");
            DropColumn("dbo.Order_d", "UnitPrice");
            DropColumn("dbo.Order_d", "CostPrice");
            DropColumn("dbo.Order_d", "ProdUnit");
            DropColumn("dbo.Order_d", "ProdSpec");
            DropColumn("dbo.Order_d", "ProdName");
            DropColumn("dbo.Order_d", "ProductID");
            DropColumn("dbo.Order_d", "QuoteSeq");
            DropColumn("dbo.Order_d", "QuoteNo");
            DropColumn("dbo.Order_d", "OrderSeq");
            DropColumn("dbo.Order_d", "OrderNo");
            DropColumn("dbo.Order_d", "CompanyID");
            DropColumn("dbo.LongOrder_m", "ModifyDateTime");
            DropColumn("dbo.LongOrder_m", "ModifyUserID");
            DropColumn("dbo.LongOrder_m", "CreateDateTime");
            DropColumn("dbo.LongOrder_m", "CreateUserID");
            DropColumn("dbo.LongOrder_m", "DataStatus");
            DropColumn("dbo.LongOrder_m", "Memo");
            DropColumn("dbo.LongOrder_m", "CycleHour");
            DropColumn("dbo.LongOrder_m", "CycleMonth");
            DropColumn("dbo.LongOrder_m", "CycleWeek");
            DropColumn("dbo.LongOrder_m", "CycleDay");
            DropColumn("dbo.LongOrder_m", "DatetimeE");
            DropColumn("dbo.LongOrder_m", "DatetimeS");
            DropColumn("dbo.LongOrder_m", "OrderNo");
            DropColumn("dbo.LongOrder_m", "LongOrderNo");
            DropColumn("dbo.LongOrder_m", "CompanyID");
            DropColumn("dbo.Factories", "ModifyDateTime");
            DropColumn("dbo.Factories", "ModifyUserID");
            DropColumn("dbo.Factories", "CreateDateTime");
            DropColumn("dbo.Factories", "CreateUserID");
            DropColumn("dbo.Factories", "InValidDate");
            DropColumn("dbo.Factories", "Memo");
            DropColumn("dbo.Factories", "PayCode");
            DropColumn("dbo.Factories", "PayTerms");
            DropColumn("dbo.Factories", "Account2");
            DropColumn("dbo.Factories", "Account1");
            DropColumn("dbo.Factories", "FactoryType");
            DropColumn("dbo.Factories", "FactoryLevel");
            DropColumn("dbo.Factories", "Site");
            DropColumn("dbo.Factories", "TaxID");
            DropColumn("dbo.Factories", "PayDays");
            DropColumn("dbo.Factories", "PayDate");
            DropColumn("dbo.Factories", "CloseDate");
            DropColumn("dbo.Factories", "ContactEmail");
            DropColumn("dbo.Factories", "MobileNumber");
            DropColumn("dbo.Factories", "TelephoneNumber");
            DropColumn("dbo.Factories", "ContactTiitle");
            DropColumn("dbo.Factories", "ContactName");
            DropColumn("dbo.Factories", "Email");
            DropColumn("dbo.Factories", "FaxNumber");
            DropColumn("dbo.Factories", "PhoneNumber");
            DropColumn("dbo.Factories", "PhoneAreaCode");
            DropColumn("dbo.Factories", "PhoneCountryCode");
            DropColumn("dbo.Factories", "ChargeName");
            DropColumn("dbo.Factories", "FactoryAddress");
            DropColumn("dbo.Factories", "PostalCode");
            DropColumn("dbo.Factories", "FactoryName");
            DropColumn("dbo.Factories", "ShortName");
            DropColumn("dbo.Factories", "FactoryID");
            DropColumn("dbo.Factories", "CompanyID");
            DropColumn("dbo.Companies", "ModifyDateTime");
            DropColumn("dbo.Companies", "ModifyUserID");
            DropColumn("dbo.Companies", "CreateDateTime");
            DropColumn("dbo.Companies", "CreateUserID");
            DropColumn("dbo.Companies", "BusinessHourE");
            DropColumn("dbo.Companies", "BusinessHourS");
            DropColumn("dbo.Companies", "Email");
            DropColumn("dbo.Companies", "Site");
            DropColumn("dbo.Companies", "CompanyAddress");
            DropColumn("dbo.Companies", "FaxNumber");
            DropColumn("dbo.Companies", "PhoneNumber");
            DropColumn("dbo.Companies", "PhoneAreaCode");
            DropColumn("dbo.Companies", "PhoneCountryCode");
            DropColumn("dbo.Companies", "ShortName");
            DropColumn("dbo.Companies", "CompanyName");
            DropColumn("dbo.Companies", "CompanyID");
            DropColumn("dbo.CombProduct_m", "ModifyDateTime");
            DropColumn("dbo.CombProduct_m", "ModifyUserID");
            DropColumn("dbo.CombProduct_m", "CreateDateTime");
            DropColumn("dbo.CombProduct_m", "CreateUserID");
            DropColumn("dbo.CombProduct_m", "CombProdSpec");
            DropColumn("dbo.CombProduct_m", "CombProdName");
            DropColumn("dbo.CombProduct_m", "CombProductID");
            DropColumn("dbo.CombProduct_m", "CompanyID");
            DropColumn("dbo.CombProduct_d", "ModifyDateTime");
            DropColumn("dbo.CombProduct_d", "ModifyUserID");
            DropColumn("dbo.CombProduct_d", "CreateDateTime");
            DropColumn("dbo.CombProduct_d", "CreateUserID");
            DropColumn("dbo.CombProduct_d", "OtherProductID");
            DropColumn("dbo.CombProduct_d", "ProductID");
            DropColumn("dbo.CombProduct_d", "CombProdSeq");
            DropColumn("dbo.CombProduct_d", "CombProductID");
            DropColumn("dbo.CombProduct_d", "CompanyID");
            DropColumn("dbo.Codes", "ModifyDateTime");
            DropColumn("dbo.Codes", "ModifyUserID");
            DropColumn("dbo.Codes", "CreateDateTime");
            DropColumn("dbo.Codes", "CreateUserID");
            DropColumn("dbo.Codes", "CodeName");
            DropColumn("dbo.Codes", "CodeID");
            DropColumn("dbo.Codes", "CompanyID");
            DropColumn("dbo.CodeKinds", "ModifyDateTime");
            DropColumn("dbo.CodeKinds", "ModifyUserID");
            DropColumn("dbo.CodeKinds", "CreateDateTime");
            DropColumn("dbo.CodeKinds", "CreateUserID");
            DropColumn("dbo.CodeKinds", "Code_KindName");
            DropColumn("dbo.CodeKinds", "CompanyID");
            DropTable("dbo.Customers");
            AddPrimaryKey("dbo.Warehouses", new[] { "company_no", "warehouse_no" });
            AddPrimaryKey("dbo.Users", new[] { "company_no", "user_id" });
            AddPrimaryKey("dbo.UserGroup_m", new[] { "company_no", "group_id" });
            AddPrimaryKey("dbo.UserGroup_d", new[] { "company_no", "group_id", "user_id" });
            AddPrimaryKey("dbo.Stocks", new[] { "company_no", "warehouse_no", "Prod_no", "Bat_no" });
            AddPrimaryKey("dbo.Programs", new[] { "company_no", "program_id" });
            AddPrimaryKey("dbo.Products", new[] { "company_no", "Prod_no" });
            AddPrimaryKey("dbo.ProductKinds", new[] { "company_no", "Prod_kind" });
            AddPrimaryKey("dbo.Privileges", new[] { "company_no", "user_id", "program_id" });
            AddPrimaryKey("dbo.Params", new[] { "company_no", "para_kind", "para1" });
            AddPrimaryKey("dbo.Order_m", new[] { "company_no", "Order_No" });
            AddPrimaryKey("dbo.Order_d", new[] { "company_no", "Order_No", "Order_seq" });
            AddPrimaryKey("dbo.LongOrder_m", new[] { "company_no", "LongOrder_No" });
            AddPrimaryKey("dbo.Factories", new[] { "company_no", "FACT_NO" });
            AddPrimaryKey("dbo.Companies", "company_no");
            AddPrimaryKey("dbo.CombProduct_m", new[] { "company_no", "CombProd_no" });
            AddPrimaryKey("dbo.CombProduct_d", new[] { "company_no", "CombProd_no", "CombProd_seq" });
            AddPrimaryKey("dbo.Codes", new[] { "company_no", "code_kind", "code" });
            AddPrimaryKey("dbo.CodeKinds", new[] { "company_no", "code_kind" });
        }
    }
}
