// <auto-generated />
namespace OpenOrderFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _20160715_longOrderDay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20160715_longOrderDay));
        
        string IMigrationMetadata.Id
        {
            get { return "201607141702477_20160715_longOrderDay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
